services:
  postgres:
    image: 'postgres:latest'
    container_name: "${POSTGRES_CONTAINER_NAME:-ucan_app_postgres}"
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB:-mydatabase}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}'
      - 'POSTGRES_USER=${POSTGRES_USER:-myuser}'
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - app-network

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-ucan_app_localstack}"
    image: localstack/localstack:4.4.0
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      SERVICES: s3
      DEBUG: "${DEBUG:-0}"
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  localstack_data:
  postgres_data: