services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-ucan_app_localstack}"
    image: localstack/localstack:4.4.0
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      SERVICES: s3
      DEBUG: "${DEBUG:-0}"
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  localstack_data:
  postgres_data: